### ISSUE TITLE
Garbage Output

### ISSUE THREAD

**Issue by SMSmith** [totalopenstation/totalopenstation#126]
I'm working with a Leica TCRA1105+.  My main issue is the output looks like the attached.  

I'd be happy to help add support for this device but I'm struggling to understand what I'm looking at.  

Any ideas?

[test0.tops.txt](https://github.com/steko/totalopenstation/files/3947541/test0.tops.txt)

**Comment by SMSmith** [comment]
Also, is there a way to send it a command to make a recording?   I had to push the record button to get these types of jobs in the middle of the garbage:
`11....+00000061 32..11+00009805 21.324+34716230 22.324+09538240 31..01+00009853 58..16+00000231 `

**Comment by psolyca** [comment]
When looking at your file, correct values are GSI8 format.
`11....+00000061 32..11+00009805 21.324+34716230 22.324+09538240 31..01+00009853 58..16+00000231`
It is just that the transfer or conversion is not correctly handled.

What are you doing to get the file ?
Are you directly connected the station to a computer or did you transfer your file by hand ?

Which version of Tops do you use ? On what OS?

EDIT : Try to connect with TCR1205 values if you directly connect the station to the computer through Tops. It should be the same parameters.

**Comment by SMSmith** [comment]
I have a direct serial connection to the Leica and I'm running the gui version. This is the stream output as I'm in measurement mode and randomly pressing the record button. 

I tried the most recent version (5) and the 2nd most recent with the same results.

I'm running windows 10. 

I've tried custom settings and tcr1205 settings and get the same result. 

Running 19200 Baude, no parity, one stop bit.

**Comment by steko** [comment]
I think there are two separate issues here:

1. the content of the attached file shows that we have a bug in the code that puts the downloaded data inside the main window: it must call `result.decode()` (convert from bytes to string) and not `result.encode()` (pointless on bytes) - I don't know why this doesn't return an exception but it needs to be fixed (I'll do that)
2. there's a lot of data being transferred over the wire, some of it is GSI8 but most of it is in a different format - we can certainly filter out all lines starting with `//` but that doesn't seem ideal. I need to say that the total stations that I have used don't allow recording during data download so the program isn't really prepared for a continuous stream.

@SMSmith to answer your question

> Also, is there a way to send it a command to make a recording?

I'm afraid there is no way to do that at the moment, although it would be very useful.

The GSI8 content of the file is just 5 lines:
```

11....+00000061 32..11+00009805 21.324+34716230 22.324+09538240 31..01+00009853 58..16+00000231 
11....+00000062 32..11+00009805 21.324+34716320 22.324+09538050 31..01+00009853 58..16+00000231 
11....+00000063 32..11+00009805 21.324+34716330 22.324+09538040 31..01+00009853 58..16+00000231 
11....+00000064 32..11+00009802 21.324+34716320 22.324+09538020 31..01+00009849 58..16+00000231 
11....+00000065 32..11+00009805 21.324+34716320 22.324+09538020 31..01+00009853 58..16+00000231 
```

**Comment by psolyca** [comment]
@steko After a deeper analyse, I think filtering `//` lines is fine.

Sequences are pretty mush the same and values after `//` are inside the "valid" line.

```
//e/248\r\n
//g/1/0\r\n
//c/112/24/"\xf8\xf9\xfa"/0/1\r\n
//c/112/32/"\xfb\xfc\xfd"/0/1\r\n
11....+00000062 32..11+00009805 21.324+34716320 22.324+09538050 31..01+00009853 58..16+00000231 \r\n
//j/0\r\n//f/248\r\n
//g/1/0\r\n
//c/129/56/"     "/1\r\n
//c/133/56/"TEST"/1\r\n
//c/172/56/"     "/1\r\n
//c/176/56/"STOP"/1\r\n
//c/94/56/"   "/1\r\n
//c/94/56/"REC"/1\r\n
//b/0/8/231/15\r\n
//c/0/8/"Hz        :"\r\n
//c/136/8/"347\t16\'32""\r\n
//b/0/16/231/55\r\n
//c/0/16/"Horiz.Dist:"\r\n
//c/176/16/"9.805"\r\n
//c/216/16/"ft"\r\n
//c/0/24/"Refl. list:"\r\n
//c/88/24/"Leica 360\xf8 prism"/1\r\n
//c/216/24/"\x08"/1\r\n
//c/0/32/"Add.const.:"\r\n
//c/184/32/"23.1"\r\n
//c/216/32/"mm"\r\n
//c/0/40/"Target Typ:"\r\n
//c/144/40/"Reflector"\r\n
//c/216/40/"\x08"\r\n
//c/0/48/"V         :"\r\n
//c/128/48/"-  5\t38\'05""\r\n
//c/94/56/"   "/1\r\n
//c/94/56/"REC"/1\r\n
//c/129/56/"     "/1\r\n
//c/133/56/"TEST"/1\r\n
//c/172/56/"     "/1\r\n
//c/176/56/"STOP"/1\r\n
//q/29/1/6/0\r\n
//d/232/8/239/55\r\n
//b/233/9/238/54\r\n
//r/29/1/6/0\r\n
//i/0\r\n
//c/200/8/"3"\r\n
//c/200/48/"4"\r\n
//i/0\r\n
//c/200/8/"1"\r\n
//c/208/16/"2"\r\n
//e/32\r\n
//e/124\r\n
//e/164\r\n
//i/0\r\n
//c/200/8/"2"\r\n
//i/0\r\n
//i/0\r\n
//e/32\r\n
//e/124\r\n
//e/164\r\n
//s/16\r\n
//i/0\r\n
//c/129/56/"     "/1\r\n
//c/133/56/"TEST"/1\r\n
//c/172/56/"     "/1\r\n
//c/176/56/"STOP"/1\r\n
//c/94/56/"   "/1\r\n
//c/94/56/"REC"/1\r\n
//i/0\r\n
```

**Comment by SMSmith** [comment]
I've confirmed the same output occurs in Ubuntu running [minicom](https://linux.die.net/man/1/minicom).

How would I put the station in a constant polling mode?  Any method to make it keep recording so that I keep seeing the measurements?

**Comment by steko** [comment]
@SMSmith I'm not sure I understand what you mean by "constant polling mode". Would you like to be able to download data from the total station to the app while you are recording?

For reference, the current behaviour (close serial communication as soon as there's no buffered data) is controlled by this piece of code:

https://github.com/steko/totalopenstation/blob/98c278ee0f5e89f8457f009664afc69be3052afd/scripts/totalopenstation-gui.py#L748-L756

We could definitely have a switch to disable this behaviour, so that a manual "stop" 🛑 is required, if needed.
