### ISSUE TITLE
[FEATURE] Rename default git branch

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#135]
I propose we follow the official GitHub guidelines for renaming the default git branch to "main", making the change later this year. This issue is mainly to let people know we are aware of the community consensus about this change and we agree with the decision to change the default branch.

**Comment by psolyca** [comment]
OK, I was not aware of this.

**Comment by steko** [comment]
**The default branch has been renamed!**

`master` is now named `main`

If you have a local clone, you can update it by running:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
