### ISSUE TITLE
Error with a Nikon NPL-322  

### ISSUE THREAD

**Issue by baswein** [totalopenstation/totalopenstation#136]
**Describe the bug**
Thanks for all your work on this program! I am excited to use it with with my Nikon NPL-322. On other programs I use the settings for Nikon NPL-350 without problems so I was excited to see that you had that as an option. However I get this error- 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "totalopenstation-gui.py", line 759, in connect_action
  File "totalopenstation-gui.py", line 745, in connect
AttributeError: 'bytes' object has no attribute 'encode'
```
Any ideas?   

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating system: [e.g. Windows]
 - Software version [e.g. 0.4]

**Additional context**

**Comment by steko** [comment]
Thank you for helping us improve Total Open Station!
It looks like you're seeing the same problem described in #126 (in particular, the `decode` vs `encode` bug) which I thought we fixed. Apparently that is not the case :disappointed: 
I'm going to fix that right now but it may take a few days before a new release is ready. What operating system are you using?

**Comment by baswein** [comment]
@steko - Thank you so much. No particular rush on my part. 
I am on windows 10.  I am using the TOP GUI and did nothing special to set it up other than running the totalopenstation_amd64_0.5.1.exe file. So I could have missed some setup piece. 
One thing that is different in the other program I use is that the baud rate is set to 9600 and in the TOP documentation for [NPL 305](totalopenstation.readthedocs.io/en/stable/models/model_implemented.html#nikon-npl-350-nikon-npl-350) 
It says "Baudrate: higher than 19200" . Could the baud rate be producing that error?

**Comment by steko** [comment]
Waiting for review from @psolyca

**Comment by psolyca** [comment]
Reviewed and accepted ^^

**Comment by baswein** [comment]
Thanks! 
Is there a way I can try it out?

**Comment by steko** [comment]
I'm preparing a release that will include this fix. Thank you for your patience!

**Comment by psolyca** [comment]
Yep, you can download a tarball or clone with git and use it directly or copy to your existing folder.
We did not finished the auto build process yet ^^;

**Comment by steko** [comment]
> Yep, you can download a tarball or clone with git and use it directly or copy to your existing folder.
> We did not finished the auto build process yet ^^;

It appears that @baswein is using the standalone Windows app, so there is no existing folder.

**Comment by steko** [comment]
As soon as https://github.com/totalopenstation/totalopenstation/pull/138 is merged, the release will be ready.

**Comment by steko** [comment]
> One thing that is different in the other program I use is that the baud rate is set to 9600 and in the TOP documentation for [NPL 305](totalopenstation.readthedocs.io/en/stable/models/model_implemented.html#nikon-npl-350-nikon-npl-350)
> It says "Baudrate: higher than 19200" . Could the baud rate be producing that error?

@baswein I suggest you choose the "custom" option for your model and set the baudrate at 19200. All other parameters should be the same, but please let us know if it works for you.

**Comment by baswein** [comment]
@steko Thank you so much. 
I must admit that I am a little confused. 
Because yesterday I downloaded and ran total open station 0.5.5 and now I can't find that version anywhere. I assume it was a byproduct of your working on #138  and I happened to catch it at the right time. 
The good news is that it worked! 
Like you just suggested I had to use the custom option with the buadrate set to 9600. 
I was looking at how to add a model. I am currently taking a python class so I have some vague sense of what is going on with the files. 
It seem like I would only have to add a nikon_npl_322.py file with the default settings and a line in the __init__.py file.
Is that about right?

**Comment by steko** [comment]
@baswein aha good catch! Yes, there was a temporary fork to test the new workflow that creates the app. You can download the official version now from https://github.com/totalopenstation/totalopenstation/releases/tag/v0.5.2 

It would be great if you could contribute a setting for this model! The procedure is as you described, with a dedicated module `nikon_npl_322.py` and a line in `__init__.py`. There is also the documentation in `docs/models/model_implemented.rst`. We'll be waiting for a pull request from you :grinning:

**Comment by baswein** [comment]
Great - I can probably get to it this weekend. Thanks
