### ISSUE TITLE
[BUG]potential type error

### ISSUE THREAD

**Issue by pigeonsoar** [totalopenstation/totalopenstation#146]
Hi! I found a potential type error in landxml.py: line 556 `point_name = "point_" + point_id`
as  `point_id` is int, it will throw a type error when the code is executed.

**Comment by psolyca** [comment]
I will check all my strings.

But @steko as we are in 3.6+ Python version, maybe we can change all strings formatting with either f"{}" or "{}".format().
I have seen that somes are already up to date.

**Comment by steko** [comment]
I absolutely agree that we should convert all string formatting to f-strings. It's something I have been using sparsely but we should use it everywhere.

**Comment by steko** [comment]
Thank you @pigeonsoar for reporting this issue!

**Comment by steko** [comment]
This issue is already fixed, closing
