### ISSUE TITLE
[BUG] Nikon RAW 2.0 is imported with wrong/skewed geometries

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#149]
This bug report was sent on the Matrix channel by user "trevorwright0"

> I have been able to download data from my Nikon NPL 322 in Nikon RAW & Nikon Coords with no problems.
> 
> I'm able to download Nikon coords data to process into other formats, however, I can't figure the problem I'm having when I try to process the Nikon RAW 2.0 data into any other format.
> 
> The values aren't being  calculated properly.
> 
> I have verified this a few different ways with different CAD platforms and the X,Y,Z data doesn't make sense. For example, for a test, all my points are on the same elevation, and display on the same 'Z' plane when I display the Nikon Coords from a text or csv file, but when converted from the actual Nikon RAW 2.0 format, the Z values are calculated all different values, and the geometry of the X/Y values has been skewed as well.
> 
> I get the same results when trying to convert the Nikon RAW into DXF, which is ultimately what I'm trying to do.
> 
> (the weird character is the last character in the file after download - I was trying to manually delete that character but all the files I attached here are unmolested right from the machine)
> 

**Expected behavior**
Converting data in Nikon RAW 2.00 format returns the correct geometries in any output format.

**Additional context**
Attached are the plain text files and a ZIP archive with all files that were submitted by the user.

[Nikon_RAW_to_CSV_with_weird_character.csv](https://github.com/totalopenstation/totalopenstation/files/6949795/Nikon_RAW_to_CSV_with_weird_character.csv)
[Nikon_RAW_to_TEXT_with_weird_character.txt](https://github.com/totalopenstation/totalopenstation/files/6949796/Nikon_RAW_to_TEXT_with_weird_character.txt)
[Nikon_RAW_geometry_bug.zip](https://github.com/totalopenstation/totalopenstation/files/6949797/Nikon_RAW_geometry_bug.zip)

**Comment by steko** [comment]
My tests with the data and the current released version of Total Open Station don't show any of the problems described.

The only difference is that the origin point is arbitrarily set as X = 10000, Y = 10000 and Z = 100 (I think this is to avoid negative measurements right @psolyca ?). Otherwise the coordinates are equal to those in the `Nikon_Coords_with_weird_character.tops` file.

```
$ totalopenstation-cli-parser.py -i Nikon_RAW_with_weird_character.tops -o nikon_tops_05.csv -f nikon_raw_v200 -t csv
$ cat nikon_tops_05.csv 

"pid","type","point_name","x","y","z","angle","z_angle","distance","th","ih","circle","station"
0,"ST","1",10000.0,10000.0,100.0,"","","","",0.0,"",""
1,"PT","2",9998.19484645,9999.484775925317,98.39935831186757,"","","","","","",""
2,"PT","3",9998.207504235923,10001.478057399192,98.38232689938252,"","","","","","",""
3,"PT","4",10000.42917739271,10001.494913948056,98.3907507795571,"","","","","","",""
4,"PT","5",10005.373517716409,10000.9478184963,98.39367143787157,"","","","","","",""
5,"PT","6",10005.875946098955,10000.646461483238,98.40039973966643,"","","","","","",""
```

**Comment by steko** [comment]
Output from the development version is the same. Closing this as it's probably from an old version.

**Comment by psolyca** [comment]
Yes, coordinates of origin point are set to (1000,1000,100) to avoid negative values.
Maybe we can add a option to set them according to user need, default to (1000,1000,100).
