### ISSUE TITLE
Add support for Leica GSI format

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#31]
We should add support for the GSI format, popular with many Leica total stations.

See the attached file for a sample, kindly provided by Anna Hodgkinson.

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/31
- Originally reported by: Stefano Costa
- Originally created at: 2012-03-16T01:22:05.525

**Comment by steko** [comment]
_From Stefano Costa on 2012-03-20 21:14:33+00:00_

Please do not undertake this issue before #1, it's nonsense as the work would need to be done twice.

**Comment by steko** [comment]
_From Stefano Costa on 2012-05-14 14:32:25+00:00_

It is important to note that there are 2 formats known under the Leica GSI name:
- GSI8
- GSI16 (as in the attached gurob_test9.gsi)

They are only slightly different. It should be possible to support them from the same module.

**Comment by steko** [comment]
_From Stefano Costa on 2012-05-14 19:18:55+00:00_

[formats] Initial support for Leica GSI, refs issue 31.

Both GSI8 and GSI16 are supported. More work is needed to
account for the very detailed data that GSI makes available.

→ <<cset 8c61a68303357e8839d6420bccca093bd8c3cd73>>

**Comment by steko** [comment]
_From Stefano Costa on 2012-05-17 09:54:51+00:00_

[formats] Leica GSI: account for other possible data blocks 

→ [[ 63deb142e23dac8b8978003dd3f0c92759632931 |56a7d749f9da]]

**Comment by steko** [comment]
_From Stefano Costa on 2012-05-17 10:01:25+00:00_

[docs] Add documentation for leica_gsi module

→ [[ c71bef98ca18ddf4e0cf487e0e97e3c211d500e1 |af7248e3e4f0]]

**Comment by steko** [comment]
See 9e3ab032a7f51f8b91c92caaf57fce99c35c2615 and 29d2d1fe3384363e99f7ece3659e241ac448e353 by @psolyca improving coverage of GSI units.

**Comment by steko** [comment]
I think we need more data to understand the ways in which REC masks work with regard to the GSI output, such as in the case of `ih`.

**Comment by psolyca** [comment]
Ok, after some search here are default recording mask of Leica measurement:
-  TPS100 Series (TC400/600/800/900):
  - Mask1 (11, 21, 22, ….)
  - Mask2 (11,…., 81, 82, 83) 
- TPS110C/300/400/700 series:
  - WI 11..21..22..31..51..87..88..
  - WI 11..21..22..31..81..82. 83. 87
- TPS1000/1100/2000/5000 Series:
  - Mask 1 (do not know which one) but it seems 5 customize record mask could be set
- TS02/06/09 series (FlexLine):
  - WI 11..21..22..31..51..87..88..
  - WI 11..21..22..31..81..82. 83. 87
- Builder:
  - WI 11..21..22..31..51..87..88..
  - WI 11..21..22..31..81..82. 83. 87 
- Nova series:
  - GSI8 polar & crtsn -> GSI Polar and Cartesian (8 data characters) (Point ID, Hz, V, SlopeDist, PPM, E, N, Elev.)
  - GSI16 polar-> GSI Polar (16 data characters) (Point ID, Hz, V, SlopeDist, PPM, reflector height)
  - GSI16 cartesian -> GSI Cartesian (16 data characters) (E, N, Elev, Reflector Height)
  - Pt,N,E,Ht,Date -> Coordinate data (Northing BEFORE Easting)
  - Pt,E,N,Ht,Date -> Coordinate data (Easting BEFORE Northing)
  - Pseudo NMEA GGA -> Based on NMEA (National Marine Electronics Association), which is a standard for interfacing marine electronic devices.
  - GSI8 polar->  GSI Polar (8 data characters) (Point ID, Hz, V, SlopeDist, PPM)
  - GSI16 polar 2 -> GSI Polar (16 data characters) (Point ID, Hz, V, SlopeDist, PPM)

I did not find mask for base station, looking at two files there could be 2 masks:
- 11, 25, 84, 85, 86, 87, 88
- 11, 84, 85, 86, 87, 88

For more information, I need to register in Leica myworld website that I can not do (I do not have a professionnal status).

By the way, the minimal information we need are:
- for base point : 11, 84, 85, 86, 88
- for point (direct) : 11, 81, 82, 83
- for measurement (to compute points and analyse points) : 11, 21, 22, 31 or 32, 87

I will amend this comment, function of my searches.

**Comment by mux8** [comment]
Hello, I have a total station tc 307 and I have a problem with the format of gsi not showing my station and orientation measurements to solve

**Comment by steko** [comment]
Hello, thank you for contacting us. To be sure I understand your problem: you can download GSI data from the total station but the conversion doesn't work or does not include all the data you expected? If that is the case, could you upload here a copy of the data you see in TOPS? 

Il 12 gennaio 2016 12:48:38 CET, mux8 notifications@github.com ha scritto:

**Comment by psolyca** [comment]
If you want to retrieve your data for later process, you can not for the  moment. It is planned, the enhance version of the GSI parser is done but not usable now.

**Comment by mux8** [comment]
I use software leica survey office for download

**Comment by mux8** [comment]
if I want to take off meass must conver meass to idex, gsi or all format

**Comment by mux8** [comment]
I havent TOPS

**Comment by mux8** [comment]
format IDEX

HEADER
    VERSION 1.20  
    SYSTEM  "0"
    UNITS
        ANGULAR DMS
        LINEAR  METRE
        TEMP    CELSIUS
        PRESS   HPA
        TIME    DMY
    END UNITS
    PROJECT
        NAME    "111015"
        OPERATOR    "-"
        CREATION_DATE   11-10-2015/07:42:04.0
    END PROJECT
END HEADER
DATABASE
    POINTS(PointNo, PointID, East, North, Elevation, Code, Date, CLASS)
        100005, "OR1", , , ,"", 11-10-2015/07:50:33.0   ,   MEAS;
        100008, "OR1", , , ,"", 11-10-2015/07:50:43.0   ,   MEAS;
        100011, "OR1", , , ,"", 11-10-2015/07:52:49.0   ,   MEAS;
        100013, "OR1",  1000.000018,    1003.083948,    1.291706,   "", 11-10-2015/07:52:59.0   ,   MEAS;
        100014, "1",    1000.087331,    1002.929195,    1.287814,   "", 11-10-2015/07:54:07.0   ,   MEAS;
        100015, "2",    999.414788, 1002.428322,    0.630759,   "", 11-10-2015/07:55:44.0   ,   MEAS;
        100016, "OR1",  999.523621, 1001.998778,    0.654527,   "", 11-10-2015/07:58:50.0   ,   MEAS;
        100017, "OR2",  999.523492, 1001.999343,    0.654371,   "", 11-10-2015/07:59:23.0   ,   MEAS;
        100020, "OR1", , , ,"", 11-10-2015/08:02:44.0   ,   MEAS;
        100024, "A1", , , ,"",  11-10-2015/08:05:03.0   ,   MEAS;
        100028, "A1", , , ,"",  11-10-2015/08:07:13.0   ,   MEAS;
        100032, "A1", , , ,"",  31-10-2015/03:21:28.0   ,   MEAS;
        100004, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 11-10-2015/07:50:33.0   ,   FIX;
        100002, "A1",   1000.000000,    1000.000000,    1.000000,   "", 11-10-2015/07:45:00.0   ,   FIX;
        100003, "A1",   1000.000000,    1000.000000,    1.000000,   "", 11-10-2015/07:47:48.0   ,   FIX;
        100018, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 11-10-2015/08:01:12.0   ,   FIX;
        100022, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 11-10-2015/08:04:02.0   ,   FIX;
        100026, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 11-10-2015/08:06:56.0   ,   FIX;
        100030, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 31-10-2015/03:21:01.0   ,   FIX;
        100034, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 31-10-2015/03:22:26.0   ,   FIX;
        100035, "OR1",  1000.000000,    1003.083000,    1.290000,   "", 31-10-2015/03:22:49.0   ,   FIX;
        THEMINFO(PointNo, PointID, Attribute, Value)
        END THEMINFO
        ANNOTATIONS(PointNo, PointID, Annotation)
            100002, "A1",   "0";
            100003, "A1",   "0";
            100018, "OR1",  "0";
            100022, "OR1",  "0";
            100026, "OR1",  "0";
            100030, "OR1",  "0";
            100034, "OR1",  "0";
            100035, "OR1",  "0";
        END ANNOTATIONS
    END POINTS
END DATABASE
METEO
    ELEMENTS(StnNo, StnID, Date, DryTemp, AtmPress, RefCoeff)
        100003, "A1",   11-10-2015/07:42:04.0,  20.000000,  1006.000000,    0.130000;
    END ELEMENTS
END METEO
THEODOLITE
    INSTRUMENTS(Name, TheoNo, EDMNo, V_TYPE)
        "TC307",    649357, 0,  ZENITH;
    END INSTRUMENTS
    CONFIGS(CfgNo, InstrName, Date, AddConst)
        1,  "TC307",    11-10-2015/07:50:33.0,  0.000000;
    END CONFIGS
    SETUP
        STN_NO  100002
        STN_ID  "A1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
    END SLOPE
    SETUP
        STN_NO  100003
        STN_ID  "A1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
        100005, "OR1",  1,  0.000190,   88.291370,  0.000000,   0.050000,   11-10-2015/07:50:33.0,  9.911749,   107,    00001100;
        100008, "OR1",  1,  359.595920, 88.291360,  0.000000,   0.050000,   11-10-2015/07:50:43.0,  9.911749,   107,    00001100;
        100011, "OR1",  1,  359.595770, 88.285640,  0.000000,   0.050000,   11-10-2015/07:52:49.0,  9.911749,   107,    00001100;
        100013, "OR1",  1,  0.000120,   88.285650,  3.085031,   0.050000,   11-10-2015/07:52:59.0,  9.911749,   107,    00001100;
        100014, "1",    1,  1.422770,   88.284430,  2.931529,   0.050000,   11-10-2015/07:54:07.0,  9.911749,   107,    00001100;
        100015, "2",    1,  346.270140, 103.032130, 2.564125,   0.050000,   11-10-2015/07:55:44.0,  9.911749,   107,    00001100;
        100016, "OR1",  1,  346.354020, 105.073870, 2.128521,   0.050000,   11-10-2015/07:58:50.0,  9.911749,   107,    00001100;
        100017, "OR2",  1,  346.354070, 105.073860, 2.129121,   0.050000,   11-10-2015/07:59:23.0,  9.911749,   107,    00001100;
    END SLOPE
    SETUP
        STN_NO  100018
        STN_ID  "OR1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
        100020, "OR1",  1,  359.595580, 96.553250,  0.000000,   0.050000,   11-10-2015/08:02:44.0,  9.911749,   106,    00001100;
    END SLOPE
    SETUP
        STN_NO  100022
        STN_ID  "OR1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
        100024, "A1",   1,  359.595590, 96.533930,  0.000000,   0.050000,   11-10-2015/08:05:03.0,  9.911749,   106,    00001100;
    END SLOPE
    SETUP
        STN_NO  100026
        STN_ID  "OR1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
        100028, "A1",   1,  359.583040, 96.570030,  0.000000,   0.050000,   11-10-2015/08:07:13.0,  9.911749,   106,    00001100;
    END SLOPE
    SETUP
        STN_NO  100030
        STN_ID  "OR1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
        100032, "A1",   1,  43.374380,  88.424930,  0.000000,   0.050000,   31-10-2015/03:21:28.0,  9.911749,   106,    00001100;
    END SLOPE
    SETUP
        STN_NO  100034
        STN_ID  "OR1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
    END SLOPE
    SETUP
        STN_NO  100035
        STN_ID  "OR1"
        INST_HT 0.260000;
    END SETUP
    SLOPE(TgtNo, TgtID, CfgNo, Hz, Vz, SDist, RefHt, Date, Ppm, ApplType, Flags)
    END SLOPE
END THEODOLITE

**Comment by mux8** [comment]
Format gsi 1
110001+00000OR1 21.324+00000010 22.324+08828570 31..00+00003085 51....+0010+000 81..00+01000000 82..00+01003084 83..00+00001292 
110002+00000001 21.324+00142280 22.324+08828440 31..00+00002932 51....+0010+000 81..00+01000087 82..00+01002929 83..00+00001288 
110003+00000002 21.324+34627010 22.324+10303210 31..00+00002564 51....+0010+000 81..00+00999415 82..00+01002428 83..00+00000631 
110004+00000OR1 21.324+34635400 22.324+10507390 31..00+00002129 51....+0010+000 81..00+00999524 82..00+01001999 83..00+00000655 
110005+00000OR2 21.324+34635410 22.324+10507390 31..00+00002129 51....+0010+000 81..00+00999523 82..00+01001999 83..00+00000654

**Comment by mux8** [comment]
format gsi 2
*110001+0000000000000OR1 21.024+0000000000000010 22.024+0000000008828560 31..00+0000000000003085 81..00+0000000001000000 82..00+0000000001003084 83..00+0000000000001292 87...0+0000000000000050 88...0+0000000000000260
*110002+0000000000000001 21.024+0000000000142270 22.024+0000000008828440 31..00+0000000000002932 81..00+0000000001000087 82..00+0000000001002929 83..00+0000000000001288 87...0+0000000000000050 88...0+0000000000000260
*110003+0000000000000002 21.024+0000000034627010 22.024+0000000010303210 31..00+0000000000002564 81..00+0000000000999415 82..00+0000000001002428 83..00+0000000000000631 87...0+0000000000000050 88...0+0000000000000260
*110004+0000000000000OR1 21.024+0000000034635400 22.024+0000000010507380 31..00+0000000000002129 81..00+0000000000999524 82..00+0000000001001999 83..00+0000000000000655 87...0+0000000000000050 88...0+0000000000000260
*110005+0000000000000OR2 21.024+0000000034635400 22.024+0000000010507380 31..00+0000000000002129 81..00+0000000000999523 82..00+0000000001001999 83..00+0000000000000654 87...0+0000000000000050 88...0+0000000000000260

**Comment by mux8** [comment]
format all
![screenshot_7](https://cloud.githubusercontent.com/assets/16665754/12272148/169d5100-b95f-11e5-9c0e-288b23fefb5a.jpg)

**Comment by psolyca** [comment]
Just to know what do you want to do as you do not use TOPS ?
Seko is not in the support team of Leica survey office nor of the GSI format and neither I.
Futhermore, IDEX is a GPS data format that TOPS do not parse.

**Comment by steko** [comment]
As @psolyca noted, we can't help you with your data if you're using another program. However, for your information, I can load and parse the GSI data that you pasted above without any problem in TOPS. See the screenshot below of the data loaded in QGIS.

![mux8](https://cloud.githubusercontent.com/assets/40545/12279476/a116ea44-b987-11e5-8e61-0aa2574eea62.png)

**Comment by steko** [comment]
Can we consider support for GSI acceptable since fd94377ccc81072ca836465a559d07d196b66788 ? I think at the moment it is one of the formats that is _best_ supported, also thanks to several sample data files.

**Comment by psolyca** [comment]
Yes, I think we can. There is some more advanced functions (command for drawing) but I will add them later.

**Comment by steko** [comment]
Yes, that's my understanding, too. Why don't we document more extensively [in the documentation](https://github.com/steko/totalopenstation/blob/master/docs/input_formats/if_leica_gsi.rst) what is already working and what needs more work?

**Comment by psolyca** [comment]
Ok, it could be a good idea, I will do it as soon as possible as everything is already here. I could also do it for the other format.

**Comment by psolyca** [comment]
Documentation of Leica GSI format #69 
I close this issue.
