### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#32]
Once issue #29 has been fixed, all our (small set of) dependencies will be compatible with Python 3. There is no reason to stay with Python 2 when all major GNU/Linux distributions ship also Python 3. The only problems could be on OS X, for which we haven't done any testing so far in any case.

Porting to Python 3 will prove interesting especially in the area of bytes/strings conversion (we download bytes from total stations, usually).

This task is enough for a release on its own, so any other task that is not bug-fixing should be postponed when working at it.

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/32
- Originally reported by: Stefano Costa
- Originally created at: 2012-03-20T20:53:51.438

**Comment by sebastic** [comment]
Any progress on this?

Python 2 is EOL by the end of the year, and the next Debian stable release (bullseye) will likely not ship with Python 2 (and neither with totalopenstation if it doesn't support Python 3).

**Comment by psolyca** [comment]
Hey,

I do not know if steko is working on Tops anymore.

I was waiting for long time for review but nothing.

I begin to convert but never finished. Will see after summer to take the project up and running.

**Comment by steko** [comment]
Thanks for raising the question and thanks to @psolyca for the quick reply.
I am indeed not developing the software anymore, but I have plans to fix this during the summer and then I'll be happy to hand over the development to @psolyca entirely.

**Comment by steko** [comment]
I started working on the Python 3 migration here https://github.com/steko/totalopenstation/tree/32-switch-python-3

**Comment by steko** [comment]
See also the follow ups to specific issues related to the migration:

- [x] #84 cli parser fails with TypeError
- [x] #82 update documentation
- [x] #85 test suite doesn't check all possible combinations of output and input formats

**Comment by mfvescovi** [comment]
For the record: Debian bug report [#938680](https://bugs.debian.org/938680) has just been filed.

**Comment by steko** [comment]
Yes, I've been notified and I'm confident that the 0.5 release that is compatible with Python 3 (drops Python 2 entirely, actually) will be ready in a few weeks.

**Comment by steko** [comment]
A quick update: we're almost ready to release 0.5 now that the main migration to Python 3 is done and we fixed many bugs that surfaced.

**Comment by steko** [comment]
The documentation is now updated with 160bf94. The switch to Python 3 is complete and the 0.5 release will follow shortly.

**Comment by sebastic** [comment]
What's blocking the 0.5 release?

The process to remove python2 from Debian is still moving forward, and totalopenstation is on the list to be removed along with it.

**Comment by steko** [comment]
I was busy with my family in the past weeks :grinning: 

I just released Total Open Station 0.5 on PyPI https://pypi.org/project/totalopenstation/0.5.0/ and on GitHub. The official announcement will wait for a few days because I can't create the Windows portable app right now.

**Comment by mfvescovi** [comment]
Hi Stefano!

On 2019-11-30 at 07:48 (-08), Stefano Costa wrote:
> I was busy with my family in the past weeks :grinning: 
>
> I just released Total Open Station 0.5 on PyPI
> https://pypi.org/project/totalopenstation/0.5.0/ and on GitHub. The
> official announcement will wait for a few days because I can't create
> the Windows portable app right now.

I've just started working on packaging this new release and I'm facing a
failure on tests, which die due to 'missing' sample data files.

Attached, you'll find the build log I've made locally against the brand
new v0.5.0 and python 3.7.5.

Please, let me know if there's any additional info I can provide you to
fix this problem.

Cheers.


-- 
Matteo F. Vescovi

**Comment by steko** [comment]
Thank you Matteo! I'm afraid the build log got lost, could you please attach it directly from the GitHub website?

**Comment by mfvescovi** [comment]
On 2019-11-30 at 16:10 (-08), Stefano Costa wrote:
> Thank you Matteo! I'm afraid the build log got lost, could you please
> attach it directly from the GitHub website?

Oh, gosh... replying via e-mail I supposed it would have kept the
attachment... but I was wrong ;-)

Meanwhile, with the kind help provided by @sebastic, I fixed the problem
and the package was just uploaded to Debian unstable/sid archives.

Cheers.
