### ISSUE TITLE
Executables missing manpage

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#39]
A standard install of TOPS brings three executables:
- `usr/bin/totalopenstation-cli-connector`
- `usr/bin/totalopenstation-cli-parser`
- `usr/bin/totalopenstation-gui`

All should have a manpage, as required by policies in most GNU/Linux distributions (e.g. Debian, Fedora). Manpages can be generated using Sphinx setting the `man_pages` variable in `conf.py` (see the [Sphinx documentation](http://sphinx-doc.org/config.html#options-for-manual-page-output)) and using the command:

```
python setup.py build_sphinx -b man
```

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/39
- Originally reported by: Stefano Costa
- Originally created at: 2013-03-07T13:57:42.134

**Comment by psolyca** [comment]
I think this issue could be closed following this commit 00eac65248dc748a3bdfe7bde6e7d1b25ab7b5a6
