### ISSUE TITLE
Add support for RW5 format

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#42]
RW5 is the format used by Carlson SurvCE.

Specs here  http://update.carlsonsw.com/kbase_attach/372/
## Supported record types
- [x] BD Backsight Direct 
- [x] BK Backsight 
- [x] BR Backsight Reverse 
- [x] FD Foresight Direct 
- [x] FR Foresight Reverse 
- [ ] GPS GPS Position in Lat(dd.mmss) Lon(dd.mmss - Negative for West) and WGS84 Ellipsoid 
- [ ] Elv(meters) 
- [ ] JB Job 
- [x] LS Line of Sight 
- [x] MO Mode Setup 
- [x] OC Occupy 
- [ ] OF Off Center Shot 
- [x] SP Store Point 
- [x] SS Side Shot 
- [x] TR Traverse 
- [x] -- Note Record 

---
- Bitbucket: https://bitbucket.org/steko/totalopenstation/issue/42
- Originally reported by: Stefano Costa
- Originally created at: 2013-04-29T19:23:50.330

**Comment by steko** [comment]
Initial support in ac9b10b.

Our the test dataset is very limited, but the basic foundation for a complete parser is already in place.

**Comment by psolyca** [comment]
Hey,

All basic function (except GPS) is integrated in PR https://github.com/steko/totalopenstation/pull/64 (list is updated).

So this issue is fixed.
