### ISSUE TITLE
Nikon RAW V2.00 parser does not include ST points in output

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#49]
`ST` records are base points in Nikon RAW V2.00, where the Cartesian coordinates of the base point are recorded. Users expect these points to be included in the final output of TOPS.

This bug was submitted by @phma.

**Comment by phma** [comment]
If I remember right, I used the quick station command, which sets ST to (0,0,0) instead of a previously shot or entered point.

**Comment by psolyca** [comment]
I have a file from a Trimble M3 DR which do not have the `st` for the station point but have two lines like these:

> CO,TI  HOLD                                               Hz         0.0000 grd
> CO,TI  INPUT                       th          1.250 m    ih          1.500 m

I also seen these lines on other file on the internet (I will make samples files of them).
It seems, these values are from Record settings.
If I remember, we use a quick setting to have a local system with a base point set to (0,0,0) and use the recod setting to input the Hz, th and ih.
So we need to read these lines to have the correct computation of points and record base point as (0,0,0). Like others formats, base points should be included in output.

**Comment by steko** [comment]
Looking at the 3 sample data files in our repository, it seems common, but not a rule, to have one base point at (0,0,0) that appears as `ST` in the raw data.

There may be more `ST` points with different coordinates, and those will need to be included in the output for sure.

**Comment by steko** [comment]
@psolyca the `CO, TI ...` lines you describe need to be treated separately, we should open another issue :wink:
