### ISSUE TITLE
upgrading tops puts Steko's path to Python in the hashbang line

### ISSUE THREAD

**Issue by phma** [totalopenstation/totalopenstation#56]
I ran tops in the (tops) environment, found that it's an old version, and tried to upgrade. This is what happened:

(tops)phma@caracal:~/tops$ pip install -U totalopenstation
Downloading/unpacking totalopenstation from https://pypi.python.org/packages/py2/t/totalopenstation/totalopenstation-0.3.2-py2-none-any.whl#md5=5e459017598e59dde38a84524ce8c5b9
  Downloading totalopenstation-0.3.2-py2-none-any.whl (50kB): 50kB downloaded
Requirement already up-to-date: pyserial in ./lib/python2.7/site-packages (from totalopenstation)
Installing collected packages: totalopenstation
  Found existing installation: totalopenstation 0.3.1pre-8b2461bfd3ec
    Uninstalling totalopenstation:
      Successfully uninstalled totalopenstation
Successfully installed totalopenstation
Cleaning up...
(tops)phma@caracal:~/tops$ totalopenstation-gui.py &
[2] 12854
(tops)phma@caracal:~/tops$ bash: /home/phma/tops/bin/totalopenstation-gui.py: /home/steko/code/totalopenstation/env/bin/python: bad interpreter: No such file or directory

I edited the first line and it came up. Is something wrong with the installer?

**Comment by steko** [comment]
I can't check this right now but there may be a problem with the installer, it seems. Thank you for reporting this issue, I will update asap.

**Comment by steko** [comment]
Fixed in 2b8f8a760453e6e1e7595b3e34cc2836d194e52b 

The 0.3.3 release is identical to 0.3.2 but the wheel distribution works correctly. Thanks for reporting this issue and for waiting two weeks over it.
