### ISSUE TITLE
Nikon RAW V2.00 parser base point not matching documentation

### ISSUE THREAD

**Issue by psolyca** [totalopenstation/totalopenstation#62]
Hey,

Looking at the code of Nikon RAW V2.00 parser, here is the code:

> if fs[0] == 'ST':
>                x = fs[6]   # FIXME NEZ coord order shouldn't be hardcoded
>                y = fs[7]
>                z = fs[5]
>                bp = BasePoint(x=x, y=y, z=z, ih=0)

But in the documentation I [found here](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0CDwQFjADahUKEwiK-vLl1LjIAhXJtRoKHeS0D98&url=https%3A%2F%2Ffaculty.unlv.edu%2Fjensen%2FCEE_121%2Fpdf%2FTrimbleM3TotalStationUserGuideVer1.pdf&usg=AFQjCNE1QFf5NCVwyOHJedBK41omOF7UzA) the station record is like this:

> ST , stnpt , (stnid) , bspt , (bs id) , hi , bsazim , bsha
> ST Station record identifier (fixed text)
> stnpt Station point number
> (stn id) (Station ID)
> bspt Backsight point number
> (bs id) (Backsight ID)
> hi Height of instrument
> bsazim Backsight azimuth
> bsha Backsight horizontal angle

So the coordinates of the base point is not in the parsed file.

**Comment by steko** [comment]
It looks like this parser needs to be rewritten from scratch :imp: 

I will try to adapt some of the logic used in the Carlson RW5 parser (e.g. base points are stored in a dictionary with their id as key, so they can be recalled from any sideshot record later in the file).

When the backsight point number/id is empty, we have to assume (0,0,0) as base coordinates for calculating the `ST` coordinates, I think.

**Comment by steko** [comment]
The related #61 should be fixed together with this.

**Comment by psolyca** [comment]
After reading more of the document:
If you have more than one backsight for a station (3 minimum) it is for resection calculation of the station point and you should have the station coordinates.
If you have one backsight, you also need one known point for the station.
Otherwise you need an azimuth (like the CO, TI HOLD ... of issue https://github.com/steko/totalopenstation/issues/61).

So without anything, yes we can assume (0,0,0) as coordinates for base point.

For all automatic computation, we need to inform the operator to verify all coordinates and elevation.

**Comment by psolyca** [comment]
So for all parsers, coordinates of an unknown base point are (1000, 1000, 100) to avoid negativ coordinates.

This issue is fix with the https://github.com/steko/totalopenstation/pull/64.

Last thing is the resection calculation which will be added later for all parser.
