### ISSUE TITLE
Add support for Leica TC(R) 303/305/307

### ISSUE THREAD

**Issue by mach0** [totalopenstation/totalopenstation#72]
Hi! I'd like to add support for the Leica TCR.
Is there any testprogram I can look at? Any advices / manuals to read?
With the current state of the programm I unfortunately cannot even establish a connection.
So.. Where to start? Still anybody active here?

**Comment by psolyca** [comment]
Sorry for the late answer.

I am active (less in summer) but do not know about steko.
I did not test any connection to any station as I do not own one.
But a Leica TC(R) 303/305/307 should be connected the same way TCR 1205 connects, see [Leica TCR minimal manual](http://totalopenstation.readthedocs.io/en/latest/models/model_leica_tcr_1205.html) and should use the same file format, GSI.
I have worked on a new interface with better parsing but it has not been validated now.

**Comment by mach0** [comment]
@psolyca 
nevermind and thanks for the answer. I will try to connect it with the TCR1205 settings but I remember I already tried it once some month ago and got literally nothing from the basis.. 
I am using the original connector with a USB adapter in between - could that cause problems?
And - where to start if I am getting nothing or empty files?

**Comment by psolyca** [comment]
First are you on windows or *nix system ?
Could you have a try testing the connection with Leica own application on another computer (or your own) ?
Otherwise, from TPS400 series, standard settings are : 19200 Baud, 8 databit, No parity, 1 stopbit and CR/LF.
Also, I heard from steko some time ago that pySerial have been updated, so try an other version.

**Comment by mach0** [comment]
Well, I am on *nix usually, but I know that my colleagues will all use Windows (7, 10) to connect to the station. With Leicas application the connection works (but as far as I know only up to Windows XP or something like that - and they did not update that application, thats the reason I am searching for alternatives.

**Comment by psolyca** [comment]
Ok.
First could you need to know if it is your cable. So in a console use 'dmesg' and 'lsusb' to see if you have your station connected.
Then, try to connect to the station with minicom or an other serial terminal. You do not need to enter, just to see if you have the right parameters to connect.
After, we will try pySerial own tools, see https://pythonhosted.org/pyserial/tools.html and have a try.
If everything is ok, we need to fixe totalopenstation.

**Comment by mach0** [comment]
@psolyca thanks for your help, I will get the station on monday (it's currently in the other office) and will start testing than. Will keep my reports here (if it is ok to use this issue as reporting channel).

**Comment by mach0** [comment]
Hi! sorry that it took me so long. Sucess in transfering data from TCR307 to Windows 10 ;)
But I have no clue (yet) about the format.
What I get is:

```
110001+00063114 21.023+15927850 22.023+08703650 31...0+00015586 51....+0000+000 87...0+00001550 88....+00000000 
110002+00063113 21.023+07558950 22.023+08336500 31...0+00012481 51....+0000+000 87...0+00001550 88....+00000000 
110003+00063109 21.023+29796900 22.023+09776950 31...0+00052814 51....+0000+000 87...0+00001550 88....+00000000 
```

Is that GSI format?
I tried using the "process data" button and save it as either dxf ot txt but both files are empty but I might do something wrong.
Not tested with linux yet as I only have Windows 10 available @work.
As a tip - I connect with a Prolific 2303 chipset which does not work under windows10 with the latest driver version (3.8) but if you install driver for the PL chipset with version 2.3 everything works.
Driver is available from here: http://www.miklor.com/COM/UV_Drivers.php#install
Credits to: http://pdxpiedmont.net/node/52

So how can I add my TCR307 as an option now?
I tested both Leica download options: tcr_705 and tcr_1205 and both download exactly the same data.
And it is nice to see that it is working with windows too - maybe I can work a bit on the optics too.

**Comment by psolyca** [comment]
Hey !

This is a GSI8 format see http://totalopenstation.readthedocs.io/en/latest/input_formats/if_leica_gsi.html
I have a better documentation but not available for now, I will try to publishe it soon.

I have done lots of work on Tops (GSI parser has been enhanced) but as steko is not available for a long time nothing have been approved.
So if you are patient, during the week, I will try to publish some extra things (I am at work) with better parsing and documentation.
For now you can try parsing with GSI8 format. If it is simple data, you will not have trouble. Can you provide us your data to analyse it ?

**Comment by mach0** [comment]
Perfect, I already managed to get the data written as dxf - but it creates a layer for every pointname, point, and (i assume it is) height.
And all points are on level 0.00 (which is not useable for me).
I would need all points on the same layer in dxf and Z should be the height of the point and not only written.
If @steko is not available right now you could publish your enhancements on your own github account so that I can test?
I cannot believe TOPS is working more reliable than the original leica software though it is missing the Z for now - but I hope I can change this.
Are there some kind of templates for export?
Thanks for all your help and putting me in the right direction.

**Comment by psolyca** [comment]
I will post all my work on my github on a test branch on the week.

For DXF, I did not improve the parser cause I did not have feedback. So with your comment, I will try to manage layer on DXF.
What do you mean by templates ? For now, everything is automatic for conversion from a format to an other. I am (2 month ago) on my way to enhance the interface and then I will be able to improve conversion. It is not my priority for now.

**Comment by mach0** [comment]
Hi! sounds great. If I can help anywhere just let me know.
It'll be great to have a TCR307 menu point (allthough it seems that either 705 and 1205 is working).

with templates I meant like for e.g. dxf export: set the points flat (zero height) or assign the correct height (Z) value to make a 3d polyline later.

I'm not a professional but I can do a little python coding. So if I can help somewhere just drop me a note ..

**Comment by mach0** [comment]
I I am confident that my Leica TCR307 works with the settings - can I just add it (copy the available TCR1205 file)?

**Comment by psolyca** [comment]
If you know how to do it, you can make a PR and I will see.

**Comment by psolyca** [comment]
I have made PR for steko's repository but I have already merged my work on mine.
If you want to try the master [branch here](https://github.com/psolyca/totalopenstation) which is up to date except the interface which is far from completion.

It will be a good start to test and merge it into steko branch.
Thanks

EDIT : I did not already look at the installation method for windows (or *nux) so try a manual installation.

EDIT2 : I also updated and published improved [documentation](http://tops.readthedocs.io/en/master/) if you want to have a look.

**Comment by mach0** [comment]
I already added your repo as remote repo to my git clone..
The question is how to test it? 
I am not that familiar with .egg stuff. I found the howto with creating a virtualenv - is that still valid? can I test it that way?
I think testing for Windows is still out of scope than.
I already started to add TCR307 - but before commiting I'd like to test that too.

**Comment by steko** [comment]
Hi @mach0 I think with recent improvements by @psolyca, already merged into master, there is a chance that your use case is now working.

**Comment by steko** [comment]
Hi @mach0 I believe that the full support for your use case with GSI8 is included in Total Open Station 0.5. If you could test and confirm, it would be great (the Windows portable app will be ready shortly).

**Comment by steko** [comment]
Can we close this issue?

**Comment by psolyca** [comment]
I never had feedback but currently the parser is working.
So...

**Comment by mach0** [comment]
Just for the record, I've changed company and did not have access to that Leica anymore.
If you want I can try and ask my former colleagues to test .. But I assume everything is working ..

**Comment by steko** [comment]
@mach0 thank you, that would be much appreciated. The latest release is 0.5.2 and it's available from PyPI or as Windows portable app https://github.com/totalopenstation/totalopenstation/releases/tag/v0.5.2 

For the record, your request concerned also problems with the DXF files that are created by Total Open Station. There's a specific issue to keep track of improvements to DXF export, particularly by dropping the current custom code and adopting the ezdxf library https://github.com/totalopenstation/totalopenstation/issues/127

**Comment by mach0** [comment]
@steko 
Contacted my colleagues and got first response: 
Antivirus denied download.
I tested with virustotal and
https://www.virustotal.com/gui/file/60c1e2b181fb85238423f033d7645e618c5ad64e654df83a16ffa05509564e14/detection

From my POV this is a false positive, but is there anything which can be done on source side?

And I'll take a look at ezdxf - maybe I can help somewhere.

**Comment by steko** [comment]
> @steko
> Contacted my colleagues and got first response:
> Antivirus denied download.
> I tested with virustotal and
> https://www.virustotal.com/gui/file/60c1e2b181fb85238423f033d7645e618c5ad64e654df83a16ffa05509564e14/detection
> 
> From my POV this is a false positive, but is there anything which can be done on source side?

This is really unfortunate, thank you for letting us know. Could you please open a separate issue? 

> And I'll take a look at ezdxf - maybe I can help somewhere.

We'll be looking for your input when we start working on it.
