### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#82]
Our documentation is outdated in a few places:

- [x] the index mentions Open Moko
- [x] the index has an hardcoded reference to version 0.3: instead we should just point users to download the latest version
- [x] the index links to the old mailing list on berlios.de that doesn't exist any more
- [x] it should be very clear that the models listed in the app are not the only ones that will work with TOPS and that in most cases using the "custom" menu will work 
- [x] the installation instructions must be reviewed in detail before the 0.5 release to make sure there are no misleading references to Python 2
- [x] linking to tops-cloud as an example has potential security issues
- [x] there is no documentation about output formats
- [x] concatenate small pages to simplify documentation
- [x] add documentation for developpers

**Comment by steko** [comment]
As mentioned in #98 this update will need to include a revised documentation structure, e.g. a clear separation between user manual and development manual.

**Comment by psolyca** [comment]
In the documentation, do we call the app "Total Open Station" or "TotalOpenStation" both are present and I think homogenizing the name could be a good point but which one to take ?

**Comment by steko** [comment]
The current and correct version is "Total Open Station". The camel-case version is the old one 🐫
