### ISSUE TITLE
Leica GSI parser contains print call

### ISSUE THREAD

**Issue by steko** [totalopenstation/totalopenstation#89]
https://github.com/steko/totalopenstation/blob/bef412faaf52a36f1d6225d1aed8627008842fc3/totalopenstation/formats/leica_gsi.py#L351

Print calls must be avoided in this context (this is not a user interface). Instead we can use `import logging` and emit a _warning_ or _info_ message.

Apart from this, the code is also malformed.

**Comment by psolyca** [comment]
Yes and I think logging could be used also elsewhere to debug.

**Comment by steko** [comment]
Closed with 7d9964b
